# Generated by Django 6.0.6 on 2026-06-21 16:15

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('workspaces', '0002_workspacemember_role_fk'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('slug', models.SlugField(max_length=255, verbose_name='slug')),
                ('country', models.CharField(blank=True, max_length=2, verbose_name='country')),
                ('market', models.CharField(blank=True, max_length=2, verbose_name='market')),
                ('primary_genre', models.CharField(blank=True, max_length=80, verbose_name='primary genre')),
                ('language', models.CharField(blank=True, max_length=10, verbose_name='language')),
                ('bio_short', models.CharField(blank=True, max_length=500, verbose_name='short bio')),
                ('bio_long', models.TextField(blank=True, verbose_name='long bio')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived')], default='active', max_length=20, verbose_name='status')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('image_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artist_images', to='core.asset', verbose_name='image asset')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='workspaces.workspace')),
            ],
            options={
                'verbose_name': 'artist',
                'verbose_name_plural': 'artists',
                'ordering': ['-created_at'],
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('slug', models.SlugField(max_length=255, verbose_name='slug')),
                ('release_date', models.DateField(blank=True, null=True, verbose_name='release date')),
                ('track_type', models.CharField(choices=[('single', 'Single'), ('music_video', 'Music video'), ('album_track', 'Album track'), ('remix', 'Remix'), ('live', 'Live'), ('freestyle', 'Freestyle'), ('other', 'Other')], default='single', max_length=20, verbose_name='track type')),
                ('primary_genre', models.CharField(blank=True, max_length=80, verbose_name='primary genre')),
                ('language', models.CharField(blank=True, max_length=10, verbose_name='language')),
                ('market', models.CharField(blank=True, max_length=2, verbose_name='market')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('released', 'Released'), ('monitoring', 'Monitoring'), ('paused', 'Paused'), ('archived', 'Archived')], default='draft', max_length=20, verbose_name='status')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='catalogue.artist', verbose_name='artist')),
                ('cover_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='track_covers', to='core.asset', verbose_name='cover asset')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='workspaces.workspace')),
            ],
            options={
                'verbose_name': 'track',
                'verbose_name_plural': 'tracks',
                'ordering': ['-created_at'],
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='TrackPlatformLink',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('platform', models.CharField(choices=[('youtube', 'YouTube'), ('spotify', 'Spotify'), ('apple_music', 'Apple Music'), ('deezer', 'Deezer'), ('soundcloud', 'SoundCloud'), ('audiomack', 'Audiomack'), ('boomplay', 'Boomplay'), ('tiktok', 'TikTok'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('custom', 'Custom')], max_length=20, verbose_name='platform')),
                ('external_id', models.CharField(blank=True, max_length=255, verbose_name='external id')),
                ('url', models.URLField(max_length=1000, verbose_name='url')),
                ('canonical_url', models.URLField(blank=True, max_length=1000, verbose_name='canonical url')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('valid', 'Valid'), ('invalid', 'Invalid'), ('private', 'Private'), ('removed', 'Removed'), ('paused', 'Paused')], default='pending', max_length=20, verbose_name='status')),
                ('last_validated_at', models.DateTimeField(blank=True, null=True, verbose_name='last validated at')),
                ('validation_error', models.CharField(blank=True, max_length=500, verbose_name='validation error')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_links', to='catalogue.track', verbose_name='track')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='workspaces.workspace')),
            ],
            options={
                'verbose_name': 'track platform link',
                'verbose_name_plural': 'track platform links',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='artist',
            index=models.Index(fields=['workspace', 'status'], name='catalogue_a_workspa_a78dcb_idx'),
        ),
        migrations.AddConstraint(
            model_name='artist',
            constraint=models.UniqueConstraint(fields=('workspace', 'slug'), name='unique_artist_slug_per_workspace'),
        ),
        migrations.AddIndex(
            model_name='track',
            index=models.Index(fields=['workspace', 'status'], name='catalogue_t_workspa_ff8dab_idx'),
        ),
        migrations.AddIndex(
            model_name='track',
            index=models.Index(fields=['artist'], name='catalogue_t_artist__c38ccb_idx'),
        ),
        migrations.AddConstraint(
            model_name='track',
            constraint=models.UniqueConstraint(fields=('workspace', 'slug'), name='unique_track_slug_per_workspace'),
        ),
        migrations.AddIndex(
            model_name='trackplatformlink',
            index=models.Index(fields=['workspace', 'platform'], name='catalogue_t_workspa_5af5cf_idx'),
        ),
        migrations.AddConstraint(
            model_name='trackplatformlink',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id', ''), _negated=True), fields=('workspace', 'platform', 'external_id'), name='unique_platform_external_id_per_workspace'),
        ),
    ]
