# Generated by Django 6.0.6 on 2026-06-21 23:09

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0002_workspacemember_role_fk'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalJobReference',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_type', models.CharField(choices=[('metrics_collection', 'Metrics collection'), ('moment_detection', 'Moment detection'), ('content_generation', 'Content generation'), ('report_generation', 'Report generation'), ('media_kit_generation', 'Media kit generation'), ('video_rendering', 'Video rendering')], max_length=30, verbose_name='job type')),
                ('provider', models.CharField(choices=[('fastapi_intelligence', 'FastAPI Intelligence'), ('content_renderer', 'Content Renderer'), ('worker', 'Worker'), ('other', 'Other')], default='worker', max_length=30, verbose_name='provider')),
                ('external_job_id', models.CharField(blank=True, max_length=255, verbose_name='external job id')),
                ('related_entity_type', models.CharField(blank=True, max_length=80, verbose_name='related entity type')),
                ('related_entity_id', models.CharField(blank=True, max_length=64, verbose_name='related entity id')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=20, verbose_name='status')),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='requested at')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='completed at')),
                ('failed_at', models.DateTimeField(blank=True, null=True, verbose_name='failed at')),
                ('error_message', models.TextField(blank=True, verbose_name='error message')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_external_jobs', to=settings.AUTH_USER_MODEL, verbose_name='requested by')),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='external_jobs', to='workspaces.workspace', verbose_name='workspace')),
            ],
            options={
                'verbose_name': 'external job reference',
                'verbose_name_plural': 'external job references',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['workspace', 'status'], name='integration_workspa_66ead4_idx'), models.Index(fields=['job_type', 'status'], name='integration_job_typ_625e24_idx'), models.Index(fields=['related_entity_type', 'related_entity_id'], name='integration_related_9deb6b_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('external_job_id', ''), _negated=True), fields=('provider', 'external_job_id'), name='unique_provider_external_job_id')],
            },
        ),
    ]
