# Generated by Django 6.0.6 on 2026-06-22 01:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations_bridge', '0001_initial'),
        ('workspaces', '0002_workspacemember_role_fk'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='externaljobreference',
            name='callback_payload',
            field=models.JSONField(blank=True, default=dict, verbose_name='callback payload'),
        ),
        migrations.AddField(
            model_name='externaljobreference',
            name='callback_received_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='callback received at'),
        ),
        migrations.AddField(
            model_name='externaljobreference',
            name='idempotency_key',
            field=models.CharField(blank=True, max_length=255, verbose_name='idempotency key'),
        ),
        migrations.AddField(
            model_name='externaljobreference',
            name='request_id',
            field=models.CharField(blank=True, max_length=64, verbose_name='request id'),
        ),
        migrations.AddField(
            model_name='externaljobreference',
            name='request_payload',
            field=models.JSONField(blank=True, default=dict, verbose_name='request payload'),
        ),
        migrations.AddField(
            model_name='externaljobreference',
            name='response_payload',
            field=models.JSONField(blank=True, default=dict, verbose_name='response payload'),
        ),
        migrations.AddField(
            model_name='externaljobreference',
            name='retry_count',
            field=models.PositiveIntegerField(default=0, verbose_name='retry count'),
        ),
        migrations.AddField(
            model_name='externaljobreference',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='started at'),
        ),
        migrations.AddField(
            model_name='externaljobreference',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='submitted at'),
        ),
        migrations.AlterField(
            model_name='externaljobreference',
            name='job_type',
            field=models.CharField(choices=[('metrics_collection', 'Metrics collection'), ('moment_detection', 'Moment detection'), ('insight_generation', 'Insight generation'), ('recommendation_generation', 'Recommendation generation'), ('content_generation', 'Content generation'), ('content_preview', 'Content preview'), ('report_generation', 'Report generation'), ('media_kit_generation', 'Media kit generation'), ('video_rendering', 'Video rendering')], max_length=30, verbose_name='job type'),
        ),
        migrations.AlterField(
            model_name='externaljobreference',
            name='provider',
            field=models.CharField(choices=[('intelligence_engine', 'Intelligence Engine'), ('content_renderer', 'Content Renderer'), ('report_renderer', 'Report Renderer'), ('video_renderer', 'Video Renderer'), ('fastapi_intelligence', 'FastAPI Intelligence'), ('worker', 'Worker'), ('other', 'Other')], default='worker', max_length=30, verbose_name='provider'),
        ),
        migrations.AlterField(
            model_name='externaljobreference',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('submitted', 'Submitted'), ('running', 'Running'), ('completed', 'Completed'), ('partially_completed', 'Partially completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('timeout', 'Timeout')], default='queued', max_length=20, verbose_name='status'),
        ),
        migrations.AddIndex(
            model_name='externaljobreference',
            index=models.Index(fields=['idempotency_key', 'status'], name='integration_idempot_d19fce_idx'),
        ),
        migrations.AddIndex(
            model_name='externaljobreference',
            index=models.Index(fields=['request_id'], name='integration_request_6b4f2c_idx'),
        ),
    ]
