# Generated by Django 6.0.6 on 2026-06-21 16:29

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0001_initial'),
        ('workspaces', '0002_workspacemember_role_fk'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('slug', models.SlugField(max_length=255, verbose_name='slug')),
                ('campaign_type', models.CharField(choices=[('single_release', 'Single release'), ('music_video_release', 'Music video release'), ('album_release', 'Album release'), ('milestone_campaign', 'Milestone campaign'), ('comeback_campaign', 'Comeback campaign'), ('weekly_growth_campaign', 'Weekly growth campaign'), ('catalogue_push', 'Catalogue push'), ('media_campaign', 'Media campaign'), ('custom', 'Custom')], default='single_release', max_length=30, verbose_name='campaign type')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('archived', 'Archived')], default='draft', max_length=20, verbose_name='status')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='start date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='end date')),
                ('primary_goal', models.CharField(blank=True, max_length=120, verbose_name='primary goal')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='catalogue.artist', verbose_name='artist')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('track', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='catalogue.track', verbose_name='track')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='workspaces.workspace')),
            ],
            options={
                'verbose_name': 'campaign',
                'verbose_name_plural': 'campaigns',
                'ordering': ['-created_at'],
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='CampaignGoal',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('goal_type', models.CharField(choices=[('views', 'Views'), ('clicks', 'Clicks'), ('content_outputs', 'Content outputs'), ('milestone', 'Milestone'), ('reports', 'Reports'), ('engagement', 'Engagement'), ('custom', 'Custom')], max_length=20, verbose_name='goal type')),
                ('target_value', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='target value')),
                ('current_value', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='current value')),
                ('unit', models.CharField(blank=True, max_length=40, verbose_name='unit')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='deadline')),
                ('status', models.CharField(choices=[('active', 'Active'), ('achieved', 'Achieved'), ('missed', 'Missed'), ('cancelled', 'Cancelled')], default='active', max_length=20, verbose_name='status')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='campaigns.campaign', verbose_name='campaign')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='workspaces.workspace')),
            ],
            options={
                'verbose_name': 'campaign goal',
                'verbose_name_plural': 'campaign goals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CampaignTrack',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('reference', 'Reference'), ('catalogue_item', 'Catalogue item')], default='primary', max_length=20, verbose_name='role')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_tracks', to='campaigns.campaign', verbose_name='campaign')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_tracks', to='catalogue.track', verbose_name='track')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='workspaces.workspace')),
            ],
            options={
                'verbose_name': 'campaign track',
                'verbose_name_plural': 'campaign tracks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['workspace', 'status'], name='campaigns_c_workspa_386d83_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['artist'], name='campaigns_c_artist__e3e6eb_idx'),
        ),
        migrations.AddConstraint(
            model_name='campaign',
            constraint=models.UniqueConstraint(fields=('workspace', 'slug'), name='unique_campaign_slug_per_workspace'),
        ),
        migrations.AddIndex(
            model_name='campaigngoal',
            index=models.Index(fields=['workspace'], name='campaigns_c_workspa_918fff_idx'),
        ),
        migrations.AddIndex(
            model_name='campaigngoal',
            index=models.Index(fields=['campaign'], name='campaigns_c_campaig_8627e2_idx'),
        ),
        migrations.AddIndex(
            model_name='campaigntrack',
            index=models.Index(fields=['workspace'], name='campaigns_c_workspa_7f1a8b_idx'),
        ),
        migrations.AddConstraint(
            model_name='campaigntrack',
            constraint=models.UniqueConstraint(fields=('campaign', 'track'), name='unique_track_per_campaign'),
        ),
    ]
