# Generated by Django 6.0.6 on 2026-06-21 23:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0002_workspacemember_role_fk'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor_type', models.CharField(choices=[('user', 'User'), ('system', 'System'), ('admin', 'Admin'), ('api_key', 'API key'), ('worker', 'Worker')], default='system', max_length=20, verbose_name='actor type')),
                ('action', models.CharField(max_length=100, verbose_name='action')),
                ('entity_type', models.CharField(blank=True, max_length=80, verbose_name='entity type')),
                ('entity_id', models.CharField(blank=True, max_length=64, verbose_name='entity id')),
                ('before_data', models.JSONField(blank=True, default=dict, verbose_name='before data')),
                ('after_data', models.JSONField(blank=True, default=dict, verbose_name='after data')),
                ('ip_address_hash', models.CharField(blank=True, max_length=64, verbose_name='IP address hash')),
                ('user_agent_hash', models.CharField(blank=True, max_length=64, verbose_name='user agent hash')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL, verbose_name='actor user')),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='workspaces.workspace', verbose_name='workspace')),
            ],
            options={
                'verbose_name': 'audit event',
                'verbose_name_plural': 'audit events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['workspace', 'action'], name='audit_audit_workspa_9cc923_idx'), models.Index(fields=['entity_type', 'entity_id'], name='audit_audit_entity__0bff9a_idx'), models.Index(fields=['actor_user'], name='audit_audit_actor_u_780c9d_idx')],
            },
        ),
    ]
