# Generated by Django 6.0.6 on 2026-06-21 17:08

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
        ('catalogue', '0001_initial'),
        ('core', '0001_initial'),
        ('workspaces', '0002_workspacemember_role_fk'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentPack',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pack_key', models.SlugField(max_length=120, unique=True, verbose_name='pack key')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('pack_type', models.CharField(choices=[('release_pack', 'Release pack'), ('milestone_pack', 'Milestone pack'), ('weekly_growth_pack', 'Weekly growth pack'), ('monthly_recap_pack', 'Monthly recap pack'), ('comeback_pack', 'Comeback pack'), ('ranking_pack', 'Ranking pack'), ('auto_media_kit', 'Auto media kit'), ('label_reporting_pack', 'Label reporting pack')], max_length=30, verbose_name='pack type')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('deprecated', 'Deprecated'), ('archived', 'Archived')], default='draft', max_length=20, verbose_name='status')),
                ('is_premium', models.BooleanField(default=False, verbose_name='premium')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content_packs', to='workspaces.workspace', verbose_name='workspace')),
            ],
            options={
                'verbose_name': 'content pack',
                'verbose_name_plural': 'content packs',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ContentPackRequest',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('queued', 'Queued'), ('processing', 'Processing'), ('partially_completed', 'Partially completed'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='draft', max_length=20, verbose_name='status')),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='requested at')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='completed at')),
                ('failed_at', models.DateTimeField(blank=True, null=True, verbose_name='failed at')),
                ('error_message', models.TextField(blank=True, verbose_name='error message')),
                ('usage_event_id', models.UUIDField(blank=True, null=True, verbose_name='usage event id')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('artist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_pack_requests', to='catalogue.artist', verbose_name='artist')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_pack_requests', to='campaigns.campaign', verbose_name='campaign')),
                ('content_pack', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='content.contentpack', verbose_name='content pack')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_pack_requests', to=settings.AUTH_USER_MODEL, verbose_name='requested by')),
                ('track', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_pack_requests', to='catalogue.track', verbose_name='track')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='workspaces.workspace')),
            ],
            options={
                'verbose_name': 'content pack request',
                'verbose_name_plural': 'content pack requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('template_key', models.SlugField(max_length=120, unique=True, verbose_name='template key')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('template_type', models.CharField(choices=[('post', 'Post'), ('story', 'Story'), ('carousel', 'Carousel'), ('carousel_slide', 'Carousel slide'), ('card', 'Card'), ('thumbnail', 'Thumbnail'), ('report', 'Report'), ('media_kit', 'Media kit'), ('reel', 'Reel'), ('short', 'Short'), ('widget', 'Widget'), ('embed', 'Embed')], max_length=20, verbose_name='template type')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('deprecated', 'Deprecated'), ('archived', 'Archived')], default='draft', max_length=20, verbose_name='status')),
                ('is_premium', models.BooleanField(default=False, verbose_name='premium')),
                ('is_system', models.BooleanField(default=False, verbose_name='system')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='workspaces.workspace', verbose_name='workspace')),
            ],
            options={
                'verbose_name': 'template',
                'verbose_name_plural': 'templates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ContentPackTemplate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('output_type', models.CharField(max_length=30, verbose_name='output type')),
                ('format', models.CharField(blank=True, max_length=20, verbose_name='format')),
                ('required', models.BooleanField(default=True, verbose_name='required')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='sort order')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('content_pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pack_templates', to='content.contentpack', verbose_name='content pack')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pack_links', to='content.template', verbose_name='template')),
            ],
            options={
                'verbose_name': 'content pack template',
                'verbose_name_plural': 'content pack templates',
                'ordering': ['sort_order', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='contentpack',
            name='templates',
            field=models.ManyToManyField(blank=True, related_name='packs', through='content.ContentPackTemplate', to='content.template'),
        ),
        migrations.CreateModel(
            name='TemplateVersion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.CharField(max_length=40, verbose_name='version')),
                ('renderer_type', models.CharField(choices=[('html_svg', 'HTML/SVG'), ('satori', 'Satori'), ('sharp', 'Sharp'), ('playwright', 'Playwright'), ('remotion_still', 'Remotion still'), ('remotion_video', 'Remotion video'), ('pdf', 'PDF'), ('html_embed', 'HTML embed')], max_length=20, verbose_name='renderer type')),
                ('manifest', models.JSONField(blank=True, default=dict, verbose_name='manifest')),
                ('required_props', models.JSONField(blank=True, default=list, verbose_name='required props')),
                ('supported_formats', models.JSONField(blank=True, default=list, verbose_name='supported formats')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('deprecated', 'Deprecated'), ('archived', 'Archived')], default='draft', max_length=20, verbose_name='status')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='content.template', verbose_name='template')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'template version',
                'verbose_name_plural': 'template versions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContentOutput',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('output_type', models.CharField(max_length=30, verbose_name='output type')),
                ('format', models.CharField(blank=True, max_length=20, verbose_name='format')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('validating', 'Validating'), ('processing', 'Processing'), ('rendering', 'Rendering'), ('uploading', 'Uploading'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('archived', 'Archived')], default='queued', max_length=20, verbose_name='status')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='title')),
                ('caption', models.TextField(blank=True, verbose_name='caption')),
                ('cta', models.CharField(blank=True, max_length=255, verbose_name='CTA')),
                ('public_visibility', models.CharField(choices=[('private', 'Private'), ('workspace', 'Workspace'), ('public', 'Public'), ('unlisted', 'Unlisted')], default='private', max_length=20, verbose_name='visibility')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='expires at')),
                ('usage_event_id', models.UUIDField(blank=True, null=True, verbose_name='usage event id')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('artist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_outputs', to='catalogue.artist')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_outputs', to='campaigns.campaign', verbose_name='campaign')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('storage_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_outputs', to='core.asset', verbose_name='storage asset')),
                ('track', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_outputs', to='catalogue.track')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='workspaces.workspace')),
                ('content_pack_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outputs', to='content.contentpackrequest', verbose_name='content pack request')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outputs', to='content.template', verbose_name='template')),
                ('template_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outputs', to='content.templateversion', verbose_name='template version')),
            ],
            options={
                'verbose_name': 'content output',
                'verbose_name_plural': 'content outputs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='contentpackrequest',
            index=models.Index(fields=['workspace', 'status'], name='content_con_workspa_466b43_idx'),
        ),
        migrations.AddIndex(
            model_name='contentpackrequest',
            index=models.Index(fields=['campaign'], name='content_con_campaig_65a0e4_idx'),
        ),
        migrations.AddIndex(
            model_name='template',
            index=models.Index(fields=['workspace', 'status'], name='content_tem_workspa_bac33e_idx'),
        ),
        migrations.AddConstraint(
            model_name='contentpacktemplate',
            constraint=models.UniqueConstraint(fields=('content_pack', 'template', 'output_type'), name='unique_pack_template_output'),
        ),
        migrations.AddIndex(
            model_name='contentpack',
            index=models.Index(fields=['workspace', 'status'], name='content_con_workspa_755a59_idx'),
        ),
        migrations.AddConstraint(
            model_name='templateversion',
            constraint=models.UniqueConstraint(fields=('template', 'version'), name='unique_template_version'),
        ),
        migrations.AddIndex(
            model_name='contentoutput',
            index=models.Index(fields=['workspace', 'status'], name='content_con_workspa_4ab581_idx'),
        ),
        migrations.AddIndex(
            model_name='contentoutput',
            index=models.Index(fields=['campaign'], name='content_con_campaig_869a5b_idx'),
        ),
    ]
