# Generated by Django 6.0.6 on 2026-06-21 20:44

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0002_workspacemember_role_fk'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingWebhookEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('stripe', 'Stripe')], default='stripe', max_length=20, verbose_name='provider')),
                ('provider_event_id', models.CharField(max_length=255, verbose_name='provider event id')),
                ('event_type', models.CharField(blank=True, max_length=120, verbose_name='event type')),
                ('status', models.CharField(choices=[('received', 'Received'), ('processed', 'Processed'), ('ignored', 'Ignored'), ('failed', 'Failed'), ('duplicate', 'Duplicate')], default='received', max_length=20, verbose_name='status')),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='received at')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='processed at')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='payload')),
                ('error_message', models.TextField(blank=True, verbose_name='error message')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
            ],
            options={
                'verbose_name': 'billing webhook event',
                'verbose_name_plural': 'billing webhook events',
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['provider', 'event_type'], name='billing_bil_provide_3d89ba_idx'), models.Index(fields=['status'], name='billing_bil_status_6a402b_idx')],
                'constraints': [models.UniqueConstraint(fields=('provider', 'provider_event_id'), name='unique_provider_event_id')],
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plan_key', models.SlugField(max_length=80, unique=True, verbose_name='plan key')),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('billing_interval', models.CharField(choices=[('month', 'Monthly'), ('year', 'Yearly'), ('one_time', 'One-time'), ('custom', 'Custom')], default='month', max_length=20, verbose_name='billing interval')),
                ('base_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='base price')),
                ('currency', models.CharField(default='USD', max_length=3, verbose_name='currency')),
                ('status', models.CharField(choices=[('active', 'Active'), ('hidden', 'Hidden'), ('deprecated', 'Deprecated'), ('archived', 'Archived')], default='active', max_length=20, verbose_name='status')),
                ('is_public', models.BooleanField(default=True, verbose_name='public')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
            ],
            options={
                'verbose_name': 'plan',
                'verbose_name_plural': 'plans',
                'ordering': ['base_price', 'name'],
                'indexes': [models.Index(fields=['status', 'is_public'], name='billing_pla_status_8b0932_idx')],
            },
        ),
        migrations.CreateModel(
            name='CreditLedgerEntry',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('grant', 'Grant'), ('reserve', 'Reserve'), ('consume', 'Consume'), ('release', 'Release'), ('refund', 'Refund'), ('adjustment', 'Adjustment'), ('expiration', 'Expiration'), ('purchase', 'Purchase')], max_length=20, verbose_name='transaction type')),
                ('amount', models.DecimalField(decimal_places=4, max_digits=20, verbose_name='amount')),
                ('balance_after', models.DecimalField(decimal_places=4, max_digits=20, verbose_name='balance after')),
                ('reason', models.CharField(blank=True, max_length=255, verbose_name='reason')),
                ('related_entity_type', models.CharField(blank=True, max_length=80, verbose_name='related entity type')),
                ('related_entity_id', models.CharField(blank=True, max_length=64, verbose_name='related entity id')),
                ('idempotency_key', models.CharField(blank=True, max_length=255, verbose_name='idempotency key')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='workspaces.workspace')),
            ],
            options={
                'verbose_name': 'credit ledger entry',
                'verbose_name_plural': 'credit ledger entries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['workspace', 'transaction_type'], name='billing_cre_workspa_cc0560_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('workspace', 'idempotency_key'), name='unique_credit_idempotency_key_per_workspace')],
            },
        ),
        migrations.CreateModel(
            name='PlanFeature',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('feature_key', models.SlugField(max_length=80, verbose_name='feature key')),
                ('limit_value', models.BigIntegerField(blank=True, null=True, verbose_name='limit value')),
                ('limit_unit', models.CharField(choices=[('count', 'Count'), ('per_month', 'Per month'), ('gb', 'Gigabyte'), ('boolean', 'Boolean'), ('credits', 'Credits')], default='count', max_length=20, verbose_name='limit unit')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='enabled')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='billing.plan', verbose_name='plan')),
            ],
            options={
                'verbose_name': 'plan feature',
                'verbose_name_plural': 'plan features',
                'ordering': ['plan', 'feature_key'],
                'constraints': [models.UniqueConstraint(fields=('plan', 'feature_key'), name='unique_plan_feature')],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('manual', 'Manual'), ('stripe', 'Stripe'), ('trial', 'Trial')], default='manual', max_length=20, verbose_name='provider')),
                ('provider_subscription_id', models.CharField(blank=True, max_length=255, verbose_name='provider subscription id')),
                ('status', models.CharField(choices=[('trialing', 'Trialing'), ('active', 'Active'), ('past_due', 'Past due'), ('cancelled', 'Cancelled'), ('unpaid', 'Unpaid'), ('paused', 'Paused'), ('enterprise_manual', 'Enterprise (manual)')], default='trialing', max_length=20, verbose_name='status')),
                ('current_period_start', models.DateTimeField(blank=True, null=True, verbose_name='current period start')),
                ('current_period_end', models.DateTimeField(blank=True, null=True, verbose_name='current period end')),
                ('trial_start', models.DateTimeField(blank=True, null=True, verbose_name='trial start')),
                ('trial_end', models.DateTimeField(blank=True, null=True, verbose_name='trial end')),
                ('cancel_at_period_end', models.BooleanField(default=False, verbose_name='cancel at period end')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='billing.plan', verbose_name='plan')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='workspaces.workspace')),
            ],
            options={
                'verbose_name': 'subscription',
                'verbose_name_plural': 'subscriptions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['workspace', 'status'], name='billing_sub_workspa_dfdb44_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('provider_subscription_id', ''), _negated=True), fields=('provider', 'provider_subscription_id'), name='unique_provider_subscription_id')],
            },
        ),
        migrations.CreateModel(
            name='UsageEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=40, verbose_name='event type')),
                ('quantity', models.DecimalField(decimal_places=4, default=1, max_digits=20, verbose_name='quantity')),
                ('unit', models.CharField(blank=True, max_length=40, verbose_name='unit')),
                ('related_entity_type', models.CharField(blank=True, max_length=80, verbose_name='related entity type')),
                ('related_entity_id', models.CharField(blank=True, max_length=64, verbose_name='related entity id')),
                ('cost_units', models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='cost units')),
                ('billing_period', models.CharField(blank=True, max_length=7, verbose_name='billing period')),
                ('idempotency_key', models.CharField(blank=True, max_length=255, verbose_name='idempotency key')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='workspaces.workspace')),
            ],
            options={
                'verbose_name': 'usage event',
                'verbose_name_plural': 'usage events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['workspace', 'event_type'], name='billing_usa_workspa_ab5361_idx'), models.Index(fields=['workspace', 'billing_period'], name='billing_usa_workspa_440407_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('workspace', 'idempotency_key'), name='unique_usage_idempotency_key_per_workspace')],
            },
        ),
    ]
