# Generated by Django 6.0.6 on 2026-06-30 22:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("campaigns", "0001_initial"),
        ("content", "0001_initial"),
        ("reports", "0001_initial"),
        ("workspaces", "0002_workspacemember_role_fk"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CampaignAction",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "recommendation_ref",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=512,
                        verbose_name="recommendation reference",
                    ),
                ),
                (
                    "recommendation_snapshot",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        verbose_name="recommendation snapshot",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="title")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("content_pack", "Content pack"),
                            ("report_request", "Report request"),
                            ("media_kit_request", "Media kit request"),
                            ("manual_task", "Manual task"),
                            ("mark_reviewed", "Mark reviewed"),
                            ("dismiss", "Dismiss"),
                        ],
                        max_length=30,
                        verbose_name="action type",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In progress"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("dismissed", "Dismissed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="medium",
                        max_length=20,
                        verbose_name="priority",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("recommendation", "Recommendation"),
                            ("manual", "Manual"),
                        ],
                        default="manual",
                        max_length=20,
                        verbose_name="source",
                    ),
                ),
                (
                    "dismiss_reason",
                    models.TextField(blank=True, verbose_name="dismiss reason"),
                ),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, verbose_name="metadata"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="completed at"
                    ),
                ),
                (
                    "cancelled_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="cancelled at"
                    ),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="campaign_actions",
                        to="campaigns.campaign",
                        verbose_name="campaign",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "related_content_output",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="campaign_actions",
                        to="content.contentoutput",
                        verbose_name="related content output",
                    ),
                ),
                (
                    "related_content_pack_request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="campaign_actions",
                        to="content.contentpackrequest",
                        verbose_name="related content pack request",
                    ),
                ),
                (
                    "related_media_kit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="campaign_actions",
                        to="reports.mediakit",
                        verbose_name="related media kit",
                    ),
                ),
                (
                    "related_report",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="campaign_actions",
                        to="reports.report",
                        verbose_name="related report",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "campaign action",
                "verbose_name_plural": "campaign actions",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["workspace", "campaign"],
                        name="ca_ws_campaign_idx",
                    ),
                    models.Index(
                        fields=["workspace", "campaign", "recommendation_ref"],
                        name="ca_ws_campaign_ref_idx",
                    ),
                    models.Index(fields=["status"], name="ca_status_idx"),
                    models.Index(
                        fields=["action_type"], name="ca_action_type_idx"
                    ),
                    models.Index(fields=["created_at"], name="ca_created_at_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(
                            models.Q(("recommendation_ref", ""), _negated=True),
                            (
                                "status__in",
                                ("pending", "in_progress", "completed"),
                            ),
                        ),
                        fields=(
                            "workspace",
                            "campaign",
                            "recommendation_ref",
                            "action_type",
                        ),
                        name="unique_active_campaign_action",
                    )
                ],
            },
        ),
    ]
