# Generated by Django 6.0.6 on 2026-06-21 16:06

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0002_workspacemember_role_fk'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asset_type', models.CharField(choices=[('artist_photo', 'Artist photo'), ('cover', 'Cover'), ('logo', 'Logo'), ('template_asset', 'Template asset'), ('report_pdf', 'Report PDF'), ('media_kit_asset', 'Media kit asset'), ('uploaded_image', 'Uploaded image'), ('generated_output', 'Generated output'), ('audio_preview', 'Audio preview'), ('other', 'Other')], default='other', max_length=30, verbose_name='asset type')),
                ('storage_provider', models.CharField(choices=[('local', 'Local'), ('s3', 'Amazon S3'), ('r2', 'Cloudflare R2'), ('gcs', 'Google Cloud Storage')], default='local', max_length=20, verbose_name='storage provider')),
                ('bucket', models.CharField(blank=True, max_length=255, verbose_name='bucket')),
                ('storage_key', models.CharField(blank=True, max_length=1024, verbose_name='storage key')),
                ('file_name', models.CharField(blank=True, max_length=255, verbose_name='file name')),
                ('mime_type', models.CharField(blank=True, max_length=120, verbose_name='MIME type')),
                ('file_size_bytes', models.BigIntegerField(blank=True, null=True, verbose_name='file size (bytes)')),
                ('width', models.PositiveIntegerField(blank=True, null=True, verbose_name='width')),
                ('height', models.PositiveIntegerField(blank=True, null=True, verbose_name='height')),
                ('duration_seconds', models.FloatField(blank=True, null=True, verbose_name='duration (s)')),
                ('checksum', models.CharField(blank=True, max_length=128, verbose_name='checksum')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='workspaces.workspace')),
            ],
            options={
                'verbose_name': 'asset',
                'verbose_name_plural': 'assets',
                'ordering': ['-created_at'],
                'base_manager_name': 'all_objects',
                'indexes': [models.Index(fields=['workspace', 'asset_type'], name='core_asset_workspa_7a6e98_idx')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
