# Generated by Django 6.0.6 on 2026-07-02 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='public_url',
            field=models.URLField(blank=True, max_length=2048, verbose_name='public URL'),
        ),
    ]
