# Generated by Django 6.0.6 on 2026-06-21 17:31

import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
        ('catalogue', '0001_initial'),
        ('content', '0001_initial'),
        ('workspaces', '0002_workspacemember_role_fk'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SmartLink',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='slug')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='title')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused'), ('expired', 'Expired'), ('archived', 'Archived')], default='draft', max_length=20, verbose_name='status')),
                ('branding_enabled', models.BooleanField(default=False, verbose_name='branding enabled')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('artist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='smart_links', to='catalogue.artist')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smart_links', to='campaigns.campaign', verbose_name='campaign')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('track', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='smart_links', to='catalogue.track')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='workspaces.workspace')),
            ],
            options={
                'verbose_name': 'smart link',
                'verbose_name_plural': 'smart links',
                'ordering': ['-created_at'],
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='SmartLinkDestination',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('platform', models.CharField(choices=[('youtube', 'YouTube'), ('spotify', 'Spotify'), ('apple_music', 'Apple Music'), ('deezer', 'Deezer'), ('audiomack', 'Audiomack'), ('soundcloud', 'SoundCloud'), ('boomplay', 'Boomplay'), ('instagram', 'Instagram'), ('tiktok', 'TikTok'), ('website', 'Website'), ('custom', 'Custom')], max_length=20, verbose_name='platform')),
                ('label', models.CharField(blank=True, max_length=120, verbose_name='label')),
                ('url', models.URLField(max_length=1000, verbose_name='url')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='sort order')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('smart_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinations', to='links.smartlink', verbose_name='smart link')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='workspaces.workspace')),
            ],
            options={
                'verbose_name': 'smart link destination',
                'verbose_name_plural': 'smart link destinations',
                'ordering': ['sort_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='SmartLinkClick',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('clicked_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='clicked at')),
                ('referrer', models.URLField(blank=True, max_length=1000, verbose_name='referrer')),
                ('utm_source', models.CharField(blank=True, max_length=255, verbose_name='utm source')),
                ('utm_medium', models.CharField(blank=True, max_length=255, verbose_name='utm medium')),
                ('utm_campaign', models.CharField(blank=True, max_length=255, verbose_name='utm campaign')),
                ('utm_content', models.CharField(blank=True, max_length=255, verbose_name='utm content')),
                ('country', models.CharField(blank=True, max_length=2, verbose_name='country')),
                ('device_type', models.CharField(blank=True, max_length=20, verbose_name='device type')),
                ('browser', models.CharField(blank=True, max_length=40, verbose_name='browser')),
                ('ip_hash', models.CharField(blank=True, max_length=64, verbose_name='ip hash')),
                ('user_agent_hash', models.CharField(blank=True, max_length=64, verbose_name='user agent hash')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smart_link_clicks', to='campaigns.campaign')),
                ('content_output', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='link_clicks', to='content.contentoutput')),
                ('smart_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='links.smartlink', verbose_name='smart link')),
                ('track', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='smart_link_clicks', to='catalogue.track')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='workspaces.workspace')),
                ('destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clicks', to='links.smartlinkdestination', verbose_name='destination')),
            ],
            options={
                'verbose_name': 'smart link click',
                'verbose_name_plural': 'smart link clicks',
                'ordering': ['-clicked_at'],
            },
        ),
        migrations.AddIndex(
            model_name='smartlink',
            index=models.Index(fields=['workspace', 'status'], name='links_smart_workspa_33e8cd_idx'),
        ),
        migrations.AddIndex(
            model_name='smartlinkdestination',
            index=models.Index(fields=['smart_link', 'is_active'], name='links_smart_smart_l_5aba89_idx'),
        ),
        migrations.AddIndex(
            model_name='smartlinkclick',
            index=models.Index(fields=['workspace', 'smart_link'], name='links_smart_workspa_c35bd6_idx'),
        ),
        migrations.AddIndex(
            model_name='smartlinkclick',
            index=models.Index(fields=['smart_link', 'clicked_at'], name='links_smart_smart_l_685ec5_idx'),
        ),
    ]
