# Generated by Django 6.0.6 on 2026-06-21 22:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
        ('catalogue', '0001_initial'),
        ('core', '0001_initial'),
        ('workspaces', '0002_workspacemember_role_fk'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaKit',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('generated', 'Generated'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20, verbose_name='status')),
                ('public_visibility', models.CharField(choices=[('private', 'Private'), ('workspace', 'Workspace'), ('public', 'Public'), ('unlisted', 'Unlisted')], default='private', max_length=20, verbose_name='visibility')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_kits', to='catalogue.artist', verbose_name='artist')),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_kits', to='campaigns.campaign', verbose_name='campaign')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_media_kits', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('storage_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_kits', to='core.asset', verbose_name='storage asset')),
                ('track', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_kits', to='catalogue.track', verbose_name='track')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='workspaces.workspace')),
            ],
            options={
                'verbose_name': 'media kit',
                'verbose_name_plural': 'media kits',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MediaKitItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_type', models.CharField(choices=[('bio', 'Bio'), ('stats', 'Stats'), ('image', 'Image'), ('track', 'Track'), ('link', 'Link'), ('press_quote', 'Press quote'), ('contact', 'Contact'), ('achievement', 'Achievement'), ('other', 'Other')], default='other', max_length=20, verbose_name='item type')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='title')),
                ('content', models.TextField(blank=True, verbose_name='content')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='sort order')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_kit_items', to='core.asset', verbose_name='asset')),
                ('media_kit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='reports.mediakit', verbose_name='media kit')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='workspaces.workspace')),
            ],
            options={
                'verbose_name': 'media kit item',
                'verbose_name_plural': 'media kit items',
                'ordering': ['sort_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_type', models.CharField(choices=[('weekly_report', 'Weekly report'), ('monthly_report', 'Monthly report'), ('campaign_report', 'Campaign report'), ('artist_report', 'Artist report'), ('track_report', 'Track report'), ('label_report', 'Label report'), ('catalogue_report', 'Catalogue report')], max_length=30, verbose_name='report type')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('period_start', models.DateField(blank=True, null=True, verbose_name='period start')),
                ('period_end', models.DateField(blank=True, null=True, verbose_name='period end')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('archived', 'Archived')], default='queued', max_length=20, verbose_name='status')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('artist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='catalogue.artist', verbose_name='artist')),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='campaigns.campaign', verbose_name='campaign')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_reports', to=settings.AUTH_USER_MODEL, verbose_name='requested by')),
                ('storage_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='core.asset', verbose_name='storage asset')),
                ('track', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='catalogue.track', verbose_name='track')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='workspaces.workspace')),
            ],
            options={
                'verbose_name': 'report',
                'verbose_name_plural': 'reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportSection',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('section_key', models.SlugField(max_length=120, verbose_name='section key')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='title')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='sort order')),
                ('content_json', models.JSONField(blank=True, default=dict, verbose_name='content (JSON)')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='reports.report', verbose_name='report')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='workspaces.workspace')),
            ],
            options={
                'verbose_name': 'report section',
                'verbose_name_plural': 'report sections',
                'ordering': ['sort_order', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='mediakit',
            index=models.Index(fields=['workspace', 'status'], name='reports_med_workspa_040e39_idx'),
        ),
        migrations.AddIndex(
            model_name='mediakit',
            index=models.Index(fields=['artist'], name='reports_med_artist__b42c54_idx'),
        ),
        migrations.AddIndex(
            model_name='mediakititem',
            index=models.Index(fields=['workspace'], name='reports_med_workspa_268a68_idx'),
        ),
        migrations.AddIndex(
            model_name='mediakititem',
            index=models.Index(fields=['media_kit'], name='reports_med_media_k_368a3d_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['workspace', 'status'], name='reports_rep_workspa_1fbba0_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['workspace', 'report_type'], name='reports_rep_workspa_f4b5c0_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['campaign'], name='reports_rep_campaig_27f81f_idx'),
        ),
        migrations.AddIndex(
            model_name='reportsection',
            index=models.Index(fields=['workspace'], name='reports_rep_workspa_68c851_idx'),
        ),
        migrations.AddConstraint(
            model_name='reportsection',
            constraint=models.UniqueConstraint(fields=('report', 'section_key'), name='unique_report_section_key'),
        ),
    ]
