# Generated by Django 6.0.6 on 2026-07-02 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediakit',
            name='correlation_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, verbose_name='correlation id'),
        ),
        migrations.AddField(
            model_name='report',
            name='correlation_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, verbose_name='correlation id'),
        ),
    ]
