# Generated by Django 6.0.6 on 2026-06-21 22:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0002_workspacemember_role_fk'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('report_ready', 'Report ready'), ('media_kit_ready', 'Media kit ready'), ('content_ready', 'Content ready'), ('campaign_update', 'Campaign update'), ('member_added', 'Member added'), ('billing_alert', 'Billing alert'), ('quota_alert', 'Quota alert'), ('system', 'System'), ('other', 'Other')], default='system', max_length=30, verbose_name='notification type')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('message', models.TextField(blank=True, verbose_name='message')),
                ('related_entity_type', models.CharField(blank=True, max_length=80, verbose_name='related entity type')),
                ('related_entity_id', models.CharField(blank=True, max_length=64, verbose_name='related entity id')),
                ('status', models.CharField(choices=[('unread', 'Unread'), ('read', 'Read'), ('dismissed', 'Dismissed'), ('archived', 'Archived')], default='unread', max_length=20, verbose_name='status')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='read at')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='user')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='workspaces.workspace')),
            ],
            options={
                'verbose_name': 'notification',
                'verbose_name_plural': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['workspace', 'status'], name='notificatio_workspa_99f2b3_idx'), models.Index(fields=['workspace', 'user'], name='notificatio_workspa_cc4906_idx')],
            },
        ),
    ]
